<!DOCTYPE html>
<html lang="en">
<head>
    <title>Create Your Account</title></head>
    <link rel="stylesheet" href="/assets/css/bootstrap.css">
<body>
    <h1>Create Your Account</h1>

    <?php
    if (!empty($this->errors)) {
        echo '<br><br><div class="container">';
        foreach ($this->errors as $error) {
            echo '<div class="alert alert-danger" role="alert">' . $error . '</div>';
        }
        echo '</div>';
    }
    ?>

    <form method="post" action="/Auth/create">
        <label for="username">Username:</label>
        <input type="text" id="username" name="username">
        <br><br>
        <label for="phone">Phone:</label>
        <input type="text" id="phone" name="phone">
        <br><br>
        <label for="email">Email:</label>
        <input type="text" id="email" name="email">
        <br><br>
        <label for="password">Password:</label>
        <input type="password" id="password" name="password">
        <br><br>
        <input type="submit" value="Create Account">
    </form>
</body>
</html>