<!DOCTYPE html>
<html lang="en">
<head>
    <title>Login To Your Account</title></head>
    <link rel="stylesheet" href="/assets/css/bootstrap.css">
<body>
    <h1>Login To Your Account</h1>

    <form method="post" action="/Auth/authorize">
        <label for="username">Username:</label>
        <input type="text" id="username" name="username">
        <br><br>
        <label for="password">Password:</label>
        <input type="password" id="password" name="password">
        <br><br>
        <input type="submit" value="Login">
    </form>
</body>
</html>